name: json_resolve
description: Easy resolving deep json using keypath
version: 1.0.0
author: Khoa Pham <onmyway133@gmail.com>
homepage: https://github.com/onmyway133/json_resolve

environment:
    sdk: '>=1.20.1 <3.0.0'