name: json_resolve
description: Easy resolving deep json using keypath
version: 2.0.0
author: SpooKy12
homepage: https://github.com/Spooky12/json_resolve

environment:
    sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0